# Generated by Django 5.2.4 on 2025-07-12 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_remove_product_image_url_remove_product_stock_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="name",
        ),
    ]
