# Generated by Django 5.2.4 on 2025-07-12 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_remove_product_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="audio",
            field=models.FileField(null=True, upload_to="audios/"),
        ),
    ]
